name: Bug report
description: 提交一个 BUG
body:
  - type: markdown
    attributes:
      value: |
        请按照此模版填写 BUG 界面的快照
  - type: checkboxes
    id: checkboxes
    attributes:
      label: 一些验证
      description: 在提交问题之前，请确保您完成以下操作
      options:
        - label: 检查这个问题是否属于 [本项目维护的规则](https://github.com/aoguai/subscription) 导致
          required: true
        - label: 请 **确保** 你的问题能在 [releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
          required: true
        - label: 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
          required: true
        - label: 确认知晓并同意维护者直接关闭不符合 issue 规范的问题
          required: true
        - label: 确保提供下列BUG描述及其复现步骤, 否则我同意维护者直接关闭问题
          required: true
  - type: textarea
    id: bug-1
    attributes:
      label: |
        BUG描述
      description: |
        请输入 BUG描述及其复现步骤，请使用尽量准确的描述。
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: |
        请输入 误触/不执行规则 的界面的快照, 或者生成的快照链接。
        请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭
      description: |
        快照是一个 zip 文件, 快照链接是类似 "https://i.gkd.li/import/XXXXXXXX" 或 "https://i.gkd.li/i/XXXXXXXX" 的文本, 按照如下方式可获得快照信息

        按照下面的截图示例来给界面打快照, **上传文件或者生成链接**并粘贴到下面的输入框
        ![img](https://user-images.githubusercontent.com/45487685/270372181-9e05a475-6664-4e1b-adc7-1e3973fff01f.png)
    validations:
      required: true
