name: Add Labels

on:
  issues:
    types: [opened]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.issue.body, 'i.gkd.li/import') == false &&
      contains(github.event.issue.body, 'i.gkd.li/i/') == false &&
      contains(github.event.issue.body, '.zip') == false
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'need info'
      - name: Create comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            你好 ${{ github.event.issue.user.login }}。由于您的 Issue 缺少必要的快照信息。请在评论中提供更多信息，以便我们更好地帮助您。谢谢！

            Hello ${{ github.event.issue.user.login }}. Due to the lack of necessary snapshot information in your Issue, please provide more information in the comment so that we can better assist you. Thank you!
